config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   # root "problems#index"
   #
   # get "problems" => "problems#index"
   # get "problem/:id" => "problem#show"

  resources :problems
  resources :plumbers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plumber.rb
class Plumber < ApplicationRecord
  belongs_to :problem
end

app/models/problem.rb
class Problem < ApplicationRecord
   has_many :plumbers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plumbers_controller.rb
class PlumbersController < ApplicationController
  def index
    @plumbers = Plumber.all
  end
  def show
    @plumber = Plumber.find(params[:id])
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def index
    @problems = Problem.all
  end
  def show
    @problem = Problem.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plumbers_helper.rb
module PlumbersHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paulsplumbers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee|Montserrat" rel="stylesheet">
  </head>

  <body>
    <header>
      <dev class="nav-bar-total">
        <a class="top-title-webpage"> Pauls Plumbers </a>
        <a class="nav-bar"> <%= link_to "See all problems", problems_path %></a>
        <a class="nav-bar"> <%= link_to "See all plumbers", plumbers_path %></a>
      </dev>
    </header>

    <%= yield %>

    <footer> <p class="copyright"> &copy The content of the website is copyright protected All rights reserverd
    </p></footer>

  </body>
</html>

app/views/plumbers/index.html.erb
  <div class="plumbers-banner">
  </div>

  <div class="plumbers-gallery">
    <% @plumbers.each do |plumber| %>
    <div class="plumber-card">
    <h1 class= "plumber-image"><%= plumber.name %></h1>
    <p><%= image_tag plumber.image_url %></p>

    <p class="plumber-button"> <%= link_to "see details of this plumber", plumber_path(plumber.id) %></p>
    </div>
<% end %>
</div>

app/views/plumbers/show.html.erb
<dev>
<h1><%= @plumber.name %></h1>
</dev>

<dev>
  <p>plumber name: <%= @plumber.name %></p>
  <p><%= image_tag @plumber.image_url %></p>
</dev>

app/views/problems/index.html.erb
<section class="problems-banner">
  <p>We Solve an awesome amount of problems!</p>
</section>

<div class="problems-gallery">
  <% @problems.each do |problem| %>
  <div class="problem-card">
  <p><%= problem.name %></p>
  <p class= "problem-image"><%= image_tag problem.image_url %></p>

  <a class="problem-button"> <%= link_to "About this problem", problem_path(problem.id) %></a>
  </div>
<% end %>
</div>

app/views/problems/show.html.erb
<head>
</head>
<body>
<div class="Problem-banner-show">
  <h1><%= @problem.name %></h1>
</div>

<div class="problem-page-image">
  <%= image_tag @problem.image_url %>
</div>

<div class="problem-description-box">
  <p>Description: <%= @problem.description %></p>
</div>

<div class="plumber-box-show">
  <p>Plumber for your problem:</p>
  <% @problem.plumbers.each do | plumber| %>
    <p><%= plumber.name %></p>
    <p class="plumber-problem-image"><%= image_tag plumber.image_url %></p>
  <%end%>
</div>
</body>